//----------------------------------------------------------------------
// RegAddress.h:
//   Definition of register address and address offset
//
//          Copyright (C) 2020-2029 by Jun Mo, All rights reserved.
//
//----------------------------------------------------------------------

#ifndef __REG_ADDRESS_H__
#define __REG_ADDRESS_H__
//////////////////////////////////////////////////
// define register address offset value
//////////////////////////////////////////////////
// for Global registers
#define ADDR_OFFSET_BB_ENABLE		0x0
#define ADDR_OFFSET_BB_RESET		0x4
#define ADDR_OFFSET_FIFO_CLEAR		0x8
#define ADDR_OFFSET_TRACKING_START	0xc
#define ADDR_OFFSET_MEAS_NUMBER		0x10
#define ADDR_OFFSET_MEAS_COUNT		0x14
#define ADDR_OFFSET_INTERRUPT_FLAG	0x18
#define ADDR_OFFSET_REQUEST_COUNT	0x1c
#define ADDR_OFFSET_INTERRUPT_MASK	0x20

// for IF interface
/*#define ADDR_OFFSET_IF_DATA_BITS	0x0
#define ADDR_OFFSET_IF_DATA_FORMAT	0x4*/

// for PreProcess
/*#define ADDR_OFFSET_PP_CTRL			0x0
#define ADDR_OFFSET_PP_CARR_FREQ	0x4
#define ADDR_OFFSET_PP_CARR_PHASE	0x8
#define ADDR_OFFSET_PP_COEF0_3		0x10
#define ADDR_OFFSET_PP_COEF4_7		0x14
#define ADDR_OFFSET_PP_AGC_CTRL		0x20
#define ADDR_OFFSET_PP_AGC_TH		0x24
#define ADDR_OFFSET_PP_AGC_SAMPLE	0x28
#define ADDR_OFFSET_PP_NOISE_CTRL	0x30
#define ADDR_OFFSET_PP_NOISE_POWER	0x34*/

// for AE FIFO
/*#define ADDR_OFFSET_AE_FIFO_CONFIG		0x0
#define ADDR_OFFSET_AE_FIFO_STATUS		0x4
#define ADDR_OFFSET_AE_FIFO_BASE_ADDR	0x8
#define ADDR_OFFSET_AE_FIFO_SIZE		0xc
#define ADDR_OFFSET_AE_FIFO_THRESHOLD	0x10
#define ADDR_OFFSET_AE_FIFO_READ_ADDR	0x14
#define ADDR_OFFSET_AE_FIFO_WRITE_ADDR	0x18
#define ADDR_OFFSET_AE_FIFO_CODE_FREQ	0x20
#define ADDR_OFFSET_AE_FIFO_CODE_PHASE	0x24
#define ADDR_OFFSET_AE_FIFO_LWADDR_CPU	0x40
#define ADDR_OFFSET_AE_FIFO_LWADDR_EM	0x44
#define ADDR_OFFSET_AE_FIFO_LWADDR_PPS	0x48*/

// for Acquire Engine
#define ADDR_OFFSET_AE_CONFIG			0x0
#define ADDR_OFFSET_AE_CONTROL			0x4
#define ADDR_OFFSET_AE_BUFFER_CONTROL	0x8
#define ADDR_OFFSET_AE_STATUS			0xc
#define ADDR_OFFSET_AE_CARRIER_FREQ		0x10
#define ADDR_OFFSET_AE_CODE_RATIO		0x14
#define ADDR_OFFSET_AE_THRESHOLD		0x18
/*#define ADDR_OFFSET_AE_PHASE_ADJUST		0x1c
#define ADDR_OFFSET_AE_FREQ_ADJUST		0x20
#define ADDR_OFFSET_AE_PRN_POLYNOMIAL	0x30
#define ADDR_OFFSET_AE_PRN_LENGTH		0x34
#define ADDR_OFFSET_AE_PRN_INIT_STATE	0x100
#define ADDR_OFFSET_AE_SEARCH_RESULT	0x180*/

// for TE FIFO
#define ADDR_OFFSET_TE_FIFO_CONFIG		0x0
#define ADDR_OFFSET_TE_FIFO_STATUS		0x4
//#define ADDR_OFFSET_TE_FIFO_BASE_ADDR	0x8
#define ADDR_OFFSET_TE_FIFO_SIZE		0xc
#define ADDR_OFFSET_TE_FIFO_GUARD		0x10
#define ADDR_OFFSET_TE_FIFO_READ_ADDR	0x14
#define ADDR_OFFSET_TE_FIFO_WRITE_ADDR	0x18
#define ADDR_OFFSET_TE_FIFO_BLOCK_SIZE	0x28
#define ADDR_OFFSET_TE_FIFO_BLOCK_ADJ	0x2c
#define ADDR_OFFSET_TE_FIFO_LWADDR_CPU	0x40
#define ADDR_OFFSET_TE_FIFO_LWADDR_EM	0x44
#define ADDR_OFFSET_TE_FIFO_LWADDR_PPS	0x48
#define ADDR_OFFSET_TE_FIFO_LWADDR_AE	0x4c

// for Tracking Engine
#define ADDR_OFFSET_TE_CHANNEL_ENABLE	0x0
#define ADDR_OFFSET_TE_COH_DATA_READY	0x4
#define ADDR_OFFSET_TE_OVERWRITE_PROTECT_CHANNEL	0x8
#define ADDR_OFFSET_TE_OVERWRITE_PROTECT_ADDR		0x10
#define ADDR_OFFSET_TE_OVERWRITE_PROTECT_VALUE		0x14
#define ADDR_OFFSET_TE_POLYNOMIAL		0x20
#define ADDR_OFFSET_TE_CODE_LENGTH		0x24
#define ADDR_OFFSET_TE_POLYNOMIAL2		0x28
#define ADDR_OFFSET_TE_CODE_LENGTH2		0x2c
#define ADDR_OFFSET_TE_NOISE_CONFIG		0x30
#define ADDR_OFFSET_TE_NOISE_FLOOR		0x34


//#define ADDR_OFFSET_		0x0

//////////////////////////////////////////////////
// define register address base value
//////////////////////////////////////////////////
// for base address of modules
#define ADDR_BASE_GLOBAL_REGS		0x0
#define ADDR_BASE_IF_INTERFACE		0x1000
#define ADDR_BASE_PRE_PROCESS		0x2000
#define ADDR_BASE_AE_FIFO			0x3000
#define ADDR_BASE_ACQUIRE_ENGINE	0x4000
#define ADDR_BASE_TE_FIFO			0x5000
#define ADDR_BASE_TRACKING_ENGINE	0x6000
#define ADDR_BASE_PERIPHERIAL		0x7000
#define ADDR_BASE_TE_BUFFER			0x8000
#define ADDR_BASE_AE_BUFFER			0xc000

//////////////////////////////////////////////////
// define register address value using base and offset
//////////////////////////////////////////////////
#define ADDR_BB_ENABLE				(ADDR_BASE_GLOBAL_REGS+ADDR_OFFSET_BB_ENABLE)
#define ADDR_BB_RESET				(ADDR_BASE_GLOBAL_REGS+ADDR_OFFSET_BB_RESET)
#define ADDR_FIFO_CLEAR				(ADDR_BASE_GLOBAL_REGS+ADDR_OFFSET_FIFO_CLEAR)
#define ADDR_TRACKING_START			(ADDR_BASE_GLOBAL_REGS+ADDR_OFFSET_TRACKING_START)
#define ADDR_MEAS_NUMBER			(ADDR_BASE_GLOBAL_REGS+ADDR_OFFSET_MEAS_NUMBER)
#define ADDR_MEAS_COUNT				(ADDR_BASE_GLOBAL_REGS+ADDR_OFFSET_MEAS_COUNT)
#define ADDR_INTERRUPT_FLAG			(ADDR_BASE_GLOBAL_REGS+ADDR_OFFSET_INTERRUPT_FLAG)
#define ADDR_REQUEST_COUNT			(ADDR_BASE_GLOBAL_REGS+ADDR_OFFSET_REQUEST_COUNT)
#define ADDR_INTERRUPT_MASK			(ADDR_BASE_GLOBAL_REGS+ADDR_OFFSET_INTERRUPT_MASK)

#define ADDR_IF_DATA_BITS			(ADDR_BASE_IF_INTERFACE+ADDR_OFFSET_IF_DATA_BITS)
#define ADDR_IF_DATA_FORMAT			(ADDR_BASE_IF_INTERFACE+ADDR_OFFSET_IF_DATA_FORMAT)

#define ADDR_PP_CTRL				(ADDR_BASE_PRE_PROCESS+ADDR_OFFSET_PP_CTRL)
#define ADDR_PP_CARR_FREQ			(ADDR_BASE_PRE_PROCESS+ADDR_OFFSET_PP_CARR_FREQ)
#define ADDR_PP_CARR_PHASE			(ADDR_BASE_PRE_PROCESS+ADDR_OFFSET_PP_CARR_PHASE)
#define ADDR_PP_COEF0_3				(ADDR_BASE_PRE_PROCESS+ADDR_OFFSET_PP_COEF0_3)
#define ADDR_PP_COEF4_7				(ADDR_BASE_PRE_PROCESS+ADDR_OFFSET_PP_COEF4_7)
#define ADDR_PP_AGC_CTRL			(ADDR_BASE_PRE_PROCESS+ADDR_OFFSET_PP_AGC_CTRL)
#define ADDR_PP_AGC_TH				(ADDR_BASE_PRE_PROCESS+ADDR_OFFSET_PP_AGC_TH)
#define ADDR_PP_AGC_SAMPLE			(ADDR_BASE_PRE_PROCESS+ADDR_OFFSET_PP_AGC_SAMPLE)
#define ADDR_PP_NOISE_CTRL			(ADDR_BASE_PRE_PROCESS+ADDR_OFFSET_PP_NOISE_CTRL)
#define ADDR_PP_NOISE_POWER			(ADDR_BASE_PRE_PROCESS+ADDR_OFFSET_PP_NOISE_POWER)

#define ADDR_AE_FIFO_CONFIG			(ADDR_BASE_AE_FIFO+ADDR_OFFSET_AE_FIFO_CONFIG)
#define ADDR_AE_FIFO_STATUS			(ADDR_BASE_AE_FIFO+ADDR_OFFSET_AE_FIFO_STATUS)
#define ADDR_AE_FIFO_BASE_ADDR		(ADDR_BASE_AE_FIFO+ADDR_OFFSET_AE_FIFO_BASE_ADDR)
#define ADDR_AE_FIFO_SIZE			(ADDR_BASE_AE_FIFO+ADDR_OFFSET_AE_FIFO_SIZE)
#define ADDR_AE_FIFO_THRESHOLD		(ADDR_BASE_AE_FIFO+ADDR_OFFSET_AE_FIFO_THRESHOLD)
#define ADDR_AE_FIFO_READ_ADDR		(ADDR_BASE_AE_FIFO+ADDR_OFFSET_AE_FIFO_READ_ADDR)
#define ADDR_AE_FIFO_WRITE_ADDR		(ADDR_BASE_AE_FIFO+ADDR_OFFSET_AE_FIFO_WRITE_ADDR)
#define ADDR_AE_FIFO_CODE_FREQ		(ADDR_BASE_AE_FIFO+ADDR_OFFSET_AE_FIFO_CODE_FREQ)
#define ADDR_AE_FIFO_CODE_PHASE		(ADDR_BASE_AE_FIFO+ADDR_OFFSET_AE_FIFO_CODE_PHASE)
#define ADDR_AE_FIFO_LWADDR_CPU		(ADDR_BASE_AE_FIFO+ADDR_OFFSET_AE_FIFO_LWADDR_CPU)
#define ADDR_AE_FIFO_LWADDR_EM		(ADDR_BASE_AE_FIFO+ADDR_OFFSET_AE_FIFO_LWADDR_EM)
#define ADDR_AE_FIFO_LWADDR_PPS		(ADDR_BASE_AE_FIFO+ADDR_OFFSET_AE_FIFO_LWADDR_PPS)

#define ADDR_AE_CONFIG				(ADDR_BASE_ACQUIRE_ENGINE+ADDR_OFFSET_AE_CONFIG)
#define ADDR_AE_CONTROL				(ADDR_BASE_ACQUIRE_ENGINE+ADDR_OFFSET_AE_CONTROL)
#define ADDR_AE_BUFFER_CONTROL		(ADDR_BASE_ACQUIRE_ENGINE+ADDR_OFFSET_AE_BUFFER_CONTROL)
#define ADDR_AE_STATUS				(ADDR_BASE_ACQUIRE_ENGINE+ADDR_OFFSET_AE_STATUS)
#define ADDR_AE_CARRIER_FREQ		(ADDR_BASE_ACQUIRE_ENGINE+ADDR_OFFSET_AE_CARRIER_FREQ)
#define ADDR_AE_CODE_RATIO			(ADDR_BASE_ACQUIRE_ENGINE+ADDR_OFFSET_AE_CODE_RATIO)
#define ADDR_AE_THRESHOLD			(ADDR_BASE_ACQUIRE_ENGINE+ADDR_OFFSET_AE_THRESHOLD)

#define ADDR_TE_FIFO_CONFIG			(ADDR_BASE_TE_FIFO+ADDR_OFFSET_TE_FIFO_CONFIG)
#define ADDR_TE_FIFO_STATUS			(ADDR_BASE_TE_FIFO+ADDR_OFFSET_TE_FIFO_STATUS)
#define ADDR_TE_FIFO_BASE_ADDR		(ADDR_BASE_TE_FIFO+ADDR_OFFSET_TE_FIFO_BASE_ADDR)
#define ADDR_TE_FIFO_SIZE			(ADDR_BASE_TE_FIFO+ADDR_OFFSET_TE_FIFO_SIZE)
#define ADDR_TE_FIFO_GUARD			(ADDR_BASE_TE_FIFO+ADDR_OFFSET_TE_FIFO_GUARD)
#define ADDR_TE_FIFO_READ_ADDR		(ADDR_BASE_TE_FIFO+ADDR_OFFSET_TE_FIFO_READ_ADDR)
#define ADDR_TE_FIFO_WRITE_ADDR		(ADDR_BASE_TE_FIFO+ADDR_OFFSET_TE_FIFO_WRITE_ADDR)
#define ADDR_TE_FIFO_BLOCK_SIZE		(ADDR_BASE_TE_FIFO+ADDR_OFFSET_TE_FIFO_BLOCK_SIZE)
#define ADDR_TE_FIFO_BLOCK_ADJ		(ADDR_BASE_TE_FIFO+ADDR_OFFSET_TE_FIFO_BLOCK_ADJ)
#define ADDR_TE_FIFO_LWADDR_CPU		(ADDR_BASE_TE_FIFO+ADDR_OFFSET_TE_FIFO_LWADDR_CPU)
#define ADDR_TE_FIFO_LWADDR_EM		(ADDR_BASE_TE_FIFO+ADDR_OFFSET_TE_FIFO_LWADDR_EM)
#define ADDR_TE_FIFO_LWADDR_PPS		(ADDR_BASE_TE_FIFO+ADDR_OFFSET_TE_FIFO_LWADDR_PPS)
#define ADDR_TE_FIFO_LWADDR_AE		(ADDR_BASE_TE_FIFO+ADDR_OFFSET_TE_FIFO_LWADDR_AE)

#define ADDR_TE_CHANNEL_ENABLE		(ADDR_BASE_TRACKING_ENGINE+ADDR_OFFSET_TE_CHANNEL_ENABLE)
#define ADDR_TE_COH_DATA_READY		(ADDR_BASE_TRACKING_ENGINE+ADDR_OFFSET_TE_COH_DATA_READY)
#define ADDR_TE_OVERWRITE_PROTECT_CHANNEL	(ADDR_BASE_TRACKING_ENGINE+ADDR_OFFSET_TE_OVERWRITE_PROTECT_CHANNEL)
#define ADDR_TE_OVERWRITE_PROTECT_ADDR		(ADDR_BASE_TRACKING_ENGINE+ADDR_OFFSET_TE_OVERWRITE_PROTECT_ADDR)
#define ADDR_TE_OVERWRITE_PROTECT_VALUE		(ADDR_BASE_TRACKING_ENGINE+ADDR_OFFSET_TE_OVERWRITE_PROTECT_VALUE)
#define ADDR_TE_POLYNOMIAL			(ADDR_BASE_TRACKING_ENGINE+ADDR_OFFSET_TE_POLYNOMIAL)
#define ADDR_TE_CODE_LENGTH			(ADDR_BASE_TRACKING_ENGINE+ADDR_OFFSET_TE_CODE_LENGTH)
#define ADDR_TE_POLYNOMIAL2			(ADDR_BASE_TRACKING_ENGINE+ADDR_OFFSET_TE_POLYNOMIAL2)
#define ADDR_TE_CODE_LENGTH2		(ADDR_BASE_TRACKING_ENGINE+ADDR_OFFSET_TE_CODE_LENGTH2)
#define ADDR_TE_NOISE_CONFIG		(ADDR_BASE_TRACKING_ENGINE+ADDR_OFFSET_TE_NOISE_CONFIG)
#define ADDR_TE_NOISE_FLOOR			(ADDR_BASE_TRACKING_ENGINE+ADDR_OFFSET_TE_NOISE_FLOOR)

//////////////////////////////////////////////////
// define state buffer address value
//////////////////////////////////////////////////
// for correlator state buffer
#define STATE_OFFSET_CARRIER_FREQ		0
#define STATE_OFFSET_CODE_FREQ			1
#define STATE_OFFSET_CORR_CONFIG		2
#define STATE_OFFSET_NH_CONFIG			3
#define STATE_OFFSET_COH_CONFIG			4
#define STATE_OFFSET_PRN_CONFIG			5
#define STATE_OFFSET_PRN_STATE			6
#define STATE_OFFSET_PRN_COUNT			7
#define STATE_OFFSET_CARRIER_PHASE		8
#define STATE_OFFSET_CARRIER_COUNT		9
#define STATE_OFFSET_CODE_PHASE			10
#define STATE_OFFSET_PRN_CODE			11
#define STATE_OFFSET_CORR_STATE			12
#define STATE_OFFSET_P_BRANCH_STATE		13
#define STATE_OFFSET_PRN_CONFIG2		14
#define STATE_OFFSET_PRN_STATE2			15
#define STATE_OFFSET_PARTIAL_ACC		16
//#define STATE_OFFSET_		0

#endif //__REG_ADDRESS_H__
